# Copyright (c) 2025, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
#
# WSO2 LLC. licenses this file to you under the Apache License,
# Version 2.0 (the "License"); you may not use this file except
# in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
# !!!TODO: Remove the old CRD permissions from the cluster role.

{{- if .Values.serviceAccount.enableServiceAccountCreation }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.roleName | default "wso2agent-role" }}
rules:
  - apiGroups: [""]
    resources: ["services","configmaps","secrets"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes","gateways"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: [ "gateway.networking.k8s.io" ]
    resources: [ "gateways/status" ]
    verbs: [ "get","patch","update" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get","list","watch","update","patch","create","delete" ]
  # NEW GW PERMISSIONS
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["backendtrafficpolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["backendtrafficpolicies/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["backendtrafficpolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["httproutefilters"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["httproutefilters/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["httproutefilters/finalizers"]
    verbs: ["update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["securitypolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["securitypolicies/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["securitypolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["envoyextensionpolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["envoyextensionpolicies/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["envoyextensionpolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["backends"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["backends/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.envoyproxy.io"]
    resources: ["backends/finalizers"]
    verbs: ["update"] 
  - apiGroups: ["dp.wso2.com"]
    resources: ["routemetadata"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routemetadata/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routemetadata/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routepolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routepolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routepolicies/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["backendtlspolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["backendtlspolicies/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["backendtlspolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: [ "gateway.networking.k8s.io" ]
    resources: [ "gateways/status" ]
    verbs: [ "get","patch","update" ]
  - apiGroups: ["configuration.konghq.com"]
    resources: ["kongplugins", "kongconsumers", "kongconsumergroups"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routepolicies/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routepolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routemetadata/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["routemetadata"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["apis"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["apis/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["apis/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["authentications"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["authentications/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["authentications/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["backends"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["backends/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["backends/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["apipolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["apipolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["apipolicies/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["interceptorservices"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["interceptorservices/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["interceptorservices/status"]
    verbs: ["get","patch","update"]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "scopes" ]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["scopes/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["scopes/status"]
    verbs: ["get","patch","update"]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "ratelimitpolicies" ]
    verbs: [ "get","list","watch","update","delete","create" ]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "ratelimitpolicies/finalizers" ]
    verbs: [ "update" ]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "ratelimitpolicies/status" ]
    verbs: [ "get","patch","update" ]
  - apiGroups: ["dp.wso2.com"]
    resources: ["tokenissuers"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["tokenissuers/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["tokenissuers/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["backendjwts"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["backendjwts/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["backendjwts/status"]
    verbs: ["get","patch","update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["gqlroutes"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["gqlroutes/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["gqlroutes/status"]
    verbs: ["get","patch","update"]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "aiproviders" ]
    verbs: [ "get","list","watch","update","delete","create" ]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "aiproviders/status" ]
    verbs: [ "get","patch","update" ]
  - apiGroups: [ "dp.wso2.com" ]
    resources: [ "aiproviders/finalizers" ]
    verbs: [ "update" ]
  - apiGroups: ["dp.wso2.com"]
    resources: ["airatelimitpolicies"]
    verbs: ["get","list","watch","update","delete","create"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["airatelimitpolicies/finalizers"]
    verbs: ["update"]
  - apiGroups: ["dp.wso2.com"]
    resources: ["airatelimitpolicies/status"]
    verbs: ["get","patch","update"]
{{- end }}